version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: koa
    image: koa
    container_name: koa-app
    restart: unless-stopped
    working_dir: /var/www/app/
    networks:
      - koa
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www/app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env

  db:
    image: postgres:13.0-alpine
    container_name: koa-db
    restart: unless-stopped
    networks:
      - koa
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:

networks:
  koa:
    driver: bridge