# Generated by Django 3.1.7 on 2023-05-17 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='points',
            field=models.TextField(help_text='Semicolon separated values', validators=[django.core.validators.RegexValidator('^-?\\d+,-?\\d+(;-?\\d+,-?\\d+)*$', message='Enter a set of points on a grid as semicolon separated values')]),
        ),
    ]
