name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy .env
        run: cp .env.dev .env
      - name: Build image
        run: docker compose up -d --build
      - name: Test
        run: docker compose exec app python manage.py test
      - name: Lint
        run: docker compose exec app flake8
      - name: Stop & remove volumes
        run: docker compose down -v